replica-hosts:
  - node1
  - node2
  - node3
  - node4
  - node5
  - node6
  - node7
  - node8

client-hosts:
  - node9

output: ./output/
measurement-interval: 1s
cpu-profile: true
mem-profile: true
replicas: 8
clients: 2
leader-rotation: fixed
